image: maven:3-openjdk-16-slim

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean package
        
deploy:
  stage: deploy
  script:
    - mvn deploy
